const SOURCES = ['REFERRAL', 'INTERNAL', 'JOB_BOARD', 'OTHER'];
const STATUSES = ['RECEIVED', 'IN_REVIEW', 'REJECTED', 'HIRED'];
const FINAL_STATUSES = ['REJECTED', 'HIRED'];
const REAPPLY_DAYS = 30;

module.exports = { SOURCES, STATUSES, FINAL_STATUSES, REAPPLY_DAYS };